### PR TITLE
Add csv to geojson converter starter for 10

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
I'm looking to get best practices in here. Worth adding file names as arguments? What else could make this example better?

Plan, after I get a good example we can break with changes in the code. Each change can be associated with a new test. That is a good workflow I think.

**Comment by urschrei** [comment]
This is more idiomatic and a bit more performant (even though there's still a UTF-8 check in there apparently)

You'll need to additionally import `Path` as per the first line. We're also using generic arguments with bounds for the input and output files, because it's more flexible, but note that trait bounds don't seem work with `extendr`. We've also discarded `unwrap()` in favour of `expect()` here.

    use std::path::Path;

    pub fn csv_to_geojson<T: AsRef<Path>>(csv_file: T, geojson_file: T) {
        let mut points = Vec::new();
        let mut reader = csv::Reader::from_path(csv_file).expect("Couldn't create CSV reader");
        let mut record = csv::ByteRecord::new();
        while reader.read_byte_record(&mut record).expect("Couldn't read CSV record") {
            points.push(Feature::from(Value::Point(vec![
                from_utf8(record.get(0).expect("couldn't retrieve x field from CSV"))
                    .expect("Invalid UTF-8 when parsing x coordinate")
                    .parse::<f64>()
                    .expect("Couldn't convert x coordinate to f64"),
                from_utf8(record.get(1).expect("couldn't retrieve y field from CSV"))
                    .expect("Invalid UTF-8 when parsing y coordinate")
                    .parse::<f64>()
                    .expect("Couldn't convert y coordinate to f64"),
            ])));
        }
        let fc = FeatureCollection {
            bbox: None,
            features: points,
            foreign_members: None,
        };
        let f = File::create(geojson_file).expect("Couldn't create output file");
        let f = BufWriter::new(f);
        serde_json::to_writer_pretty(f, &fc).expect("Couldn't write output GeoJSON to file");
    }

**Comment by Robinlovelace** [comment]
Many thanks for this @urschrei and sorry for the v. slow response.

**Comment by Robinlovelace** [comment]
Going to merge, hope to find time to work on this again soon, although high priority stuff to bosh first!

**Pull request merged**
